import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

import 'daos/activity_dao.dart';
import 'daos/assets_dao.dart';
import 'daos/collections_dao.dart';
import 'daos/playlists_dao.dart';
import 'daos/properties_dao.dart';
import 'daos/tags_dao.dart';
import 'tables/activity_log_table.dart';
import 'tables/assets_table.dart';
import 'tables/collections_table.dart';
import 'tables/playlists_table.dart';
import 'tables/properties_table.dart';
import 'tables/tags_table.dart';

export 'daos/activity_dao.dart';
export 'daos/assets_dao.dart';
export 'daos/collections_dao.dart';
export 'daos/playlists_dao.dart';
export 'daos/properties_dao.dart';
export 'daos/tags_dao.dart';
export 'tables/activity_log_table.dart';
export 'tables/assets_table.dart';
export 'tables/collections_table.dart';
export 'tables/playlists_table.dart';
export 'tables/properties_table.dart';
export 'tables/tags_table.dart';

part 'app_database.g.dart';

@DriftDatabase(
  tables: [
    Assets,
    Tags,
    AssetTags,
    Collections,
    CollectionAssets,
    PropertyDefinitions,
    AssetProperties,
    Playlists,
    PlaylistItems,
    ActivityLog,
  ],
  daos: [AssetsDao, TagsDao, CollectionsDao, ActivityDao, PropertiesDao, PlaylistsDao],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase(String dbPath)
      : super(
          driftDatabase(
            name: dbPath,
            native: DriftNativeOptions(databasePath: () async => dbPath),
          ),
        );

  // ── DAO accessors (generated by build_runner) ──────────────────────────────
  @override
  AssetsDao get assetsDao => AssetsDao(this);
  @override
  TagsDao get tagsDao => TagsDao(this);
  @override
  CollectionsDao get collectionsDao => CollectionsDao(this);
  @override
  ActivityDao get activityDao => ActivityDao(this);
  @override
  PropertiesDao get propertiesDao => PropertiesDao(this);
  @override
  PlaylistsDao get playlistsDao => PlaylistsDao(this);

  @override
  int get schemaVersion => 4;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          await m.createAll();
          await _applyPragmas();
          await _createIndexes();
          await _createFts5();
          await _createFts5Triggers();
        },
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            await customStatement(
              'ALTER TABLE assets ADD COLUMN media_title TEXT',
            );
            await customStatement(
              'ALTER TABLE assets ADD COLUMN artist TEXT',
            );
            await customStatement(
              'ALTER TABLE assets ADD COLUMN album TEXT',
            );
            await customStatement(
              'ALTER TABLE assets ADD COLUMN genre TEXT',
            );
            await customStatement(
              'ALTER TABLE assets ADD COLUMN track_number INTEGER',
            );
            await customStatement(
              'ALTER TABLE assets ADD COLUMN bitrate INTEGER',
            );
            await customStatement(
              'ALTER TABLE assets ADD COLUMN sample_rate INTEGER',
            );
            await customStatement(
              'ALTER TABLE assets ADD COLUMN author TEXT',
            );
            await customStatement(
              'ALTER TABLE assets ADD COLUMN publisher TEXT',
            );
            await customStatement(
              'ALTER TABLE assets ADD COLUMN page_count INTEGER',
            );
            await customStatement(
              'ALTER TABLE assets ADD COLUMN capture_date TEXT',
            );
            await customStatement(
              'ALTER TABLE assets ADD COLUMN camera_model TEXT',
            );
          }
          if (from < 3) {
            await m.createTable(propertyDefinitions);
            await m.createTable(assetProperties);
          }
          if (from < 4) {
            await m.createTable(playlists);
            await m.createTable(playlistItems);
          }
        },
        beforeOpen: (details) async {
          await _applyPragmas();
        },
      );

  Future<void> _applyPragmas() async {
    await customStatement('PRAGMA journal_mode=WAL');
    await customStatement('PRAGMA foreign_keys=ON');
    await customStatement('PRAGMA busy_timeout=5000');
    await customStatement('PRAGMA synchronous=NORMAL');
  }

  Future<void> _createIndexes() async {
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_assets_content_hash ON assets(content_hash)',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_assets_status ON assets(status)',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_assets_extension ON assets(extension)',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_assets_rating ON assets(rating)',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_assets_phash ON assets(phash)',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_asset_tags_tag_id ON asset_tags(tag_id)',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_collection_assets_asset_id'
      ' ON collection_assets(asset_id)',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_activity_log_time'
      ' ON activity_log(occurred_at DESC)',
    );
  }

  Future<void> _createFts5() async {
    await customStatement('''
      CREATE VIRTUAL TABLE IF NOT EXISTS assets_fts USING fts5(
        filename,
        note,
        content='assets',
        content_rowid='rowid'
      )
    ''');
  }

  Future<void> _createFts5Triggers() async {
    await customStatement('''
      CREATE TRIGGER IF NOT EXISTS assets_ai AFTER INSERT ON assets BEGIN
        INSERT INTO assets_fts(rowid, filename, note)
        VALUES (new.rowid, new.filename, new.note);
      END
    ''');
    await customStatement('''
      CREATE TRIGGER IF NOT EXISTS assets_ad AFTER DELETE ON assets BEGIN
        INSERT INTO assets_fts(assets_fts, rowid, filename, note)
        VALUES ('delete', old.rowid, old.filename, old.note);
      END
    ''');
    await customStatement('''
      CREATE TRIGGER IF NOT EXISTS assets_au AFTER UPDATE ON assets BEGIN
        INSERT INTO assets_fts(assets_fts, rowid, filename, note)
        VALUES ('delete', old.rowid, old.filename, old.note);
        INSERT INTO assets_fts(rowid, filename, note)
        VALUES (new.rowid, new.filename, new.note);
      END
    ''');
  }
}
